---
title: "Teste Shiny"
format: html
runtime: shiny
---

```{r}
library(shiny)
library(tidyverse)
df_absenteismo = read.csv('absenteismo_processed.csv')
hos <- unique(df_absenteismo$hospital_padronizado)
selectInput("hospital", "Hospital:", choices = hos, selected = hos[1])
plotOutput("Plot2")
```

```{r}
output$Plot2 <- renderPlot({
  hosp <- input$hospital
  set.seed(123)
  
  df <- df_absenteismo |>
    dplyr::filter(hospital_padronizado == hosp) |>   # filtro pelo input
    tidyr::pivot_longer(
      cols = c(Faltas, Agendamentos),
      names_to = 'Tipo',
      values_to = 'Quantidade'
    )
  
  plot(df$Quantidade ~ df$Tipo,
       main = paste("Dados de", hosp),
       xlab = "Tipo",
       ylab = "Quantidade")
})

```

```{r}
hos <- unique(df_absenteismo$hospital_padronizado)
selectInput("hospital", "Hospital:", choices = hos, selected = hos[1])
plotOutput("Plot")
```

```{r}
#| context: server
library(ggplot2)
library(tidyverse)
# dados processados sobre absenteismo
df_absenteismo = read.csv('absenteismo_processed.csv')
selectedData <- reactive({
  df_absenteismo |>
  dplyr::filter(hospital_padronizado == input$hospital)
  })
output$Plot <- renderPlot({
  set.seed(123)
  hosp <- input$hospital
  selectedData() |> 
  pivot_longer(
    cols = c(Faltas, Agendamentos),
    names_to = 'Tipo',
    values_to = 'Quantidade') |> 
  ggplot(aes(x = periodo)) +
  geom_bar(aes(y = Quantidade, fill = Tipo),
           stat = 'identity', position = 'dodge', alpha = 0.8)
})
```
